/**
 * CostDriversPanel — first-order explanation of 30d spend.
 *
 * This section intentionally focuses on cost components and concentration, not
 * raw token totals. It answers: "what is this data telling me?"
 */

import type { MetricSummary } from '@tokenomix/shared';
import { Brain, Layers, Route, Target } from 'lucide-react';
import { formatCurrency } from '../lib/formatters.js';
import { Section } from '../ui/Section.js';
import { MetricCard } from './MetricCard.js';

interface CostDriversPanelProps {
  data: MetricSummary;
}

function pct(n: number): string {
  return `${(n * 100).toFixed(1)}%`;
}

function share(part: number, total: number): number {
  return total > 0 ? part / total : 0;
}

function compactTokens(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return n.toLocaleString('en-US');
}

export function CostDriversPanel({ data }: CostDriversPanelProps) {
  const components = data.costComponents30d;
  const cacheCost = components.cacheCreationCostUsd + components.cacheReadCostUsd;
  const cacheTokens = components.cacheCreationTokens + components.cacheReadTokens;
  const outputShare = share(components.outputCostUsd, data.costUsd30d);
  const subagentShare = share(
    data.subagentCostUsd30d,
    data.mainSessionCostUsd30d + data.subagentCostUsd30d
  );

  return (
    <Section title="Cost Drivers" cols={4} gap="md">
      <MetricCard
        label="CACHE COST (30D)"
        value={formatCurrency(cacheCost)}
        context={`${pct(share(cacheCost, data.costUsd30d))} of spend - context pressure`}
        deltaPercent={null}
        icon={<Layers size={14} aria-hidden="true" className="shrink-0" />}
        tooltip={`${compactTokens(cacheTokens)} cache tokens were billed over 30 days. High cache share usually means repeated context rereads, long sessions, or broad file exploration. Graphify, narrower file reads, stricter /compact habits, and reusable project notes are relevant when this is a large share of spend.`}
      />

      <MetricCard
        label="OUTPUT COST SHARE"
        value={pct(outputShare)}
        context={`${formatCurrency(components.outputCostUsd)} generated by model output`}
        deltaPercent={null}
        icon={<Target size={14} aria-hidden="true" className="shrink-0" />}
        tooltip="This is the share of spend from assistant output tokens. A high value points to verbose code generation, large explanations, or repeated rewrites. A low value with high cache cost means the bigger issue is context being carried or reread, not answer length."
      />

      <MetricCard
        label="OPUS TO SONNET DELTA"
        value={formatCurrency(data.opusToSonnetSavings30d)}
        context="pricing-only model-routing hypothesis"
        deltaPercent={null}
        icon={<Brain size={14} aria-hidden="true" className="shrink-0" />}
        tooltip="This estimates what the same Opus-priced token usage would have cost at Sonnet rates. It is not a recommendation by itself: only route work down if matched trials keep completion quality, review defects, test pass rate, and rework stable."
      />

      <MetricCard
        label="SUBAGENT COST SHARE"
        value={pct(subagentShare)}
        context={`${formatCurrency(data.subagentCostUsd30d)} delegated-work spend`}
        deltaPercent={null}
        icon={<Route size={14} aria-hidden="true" className="shrink-0" />}
        tooltip={`${data.agentToolCalls30d.toLocaleString('en-US')} Agent tool calls were observed over 30 days. High share means delegation is a budget line, not background noise. Useful controls are per-agent budgets, tighter task scopes, and measuring whether subagents reduce main-session rework.`}
      />
    </Section>
  );
}
